version: '3.8'

services:
  db:
    image: "postgres:14.1-alpine"
    restart: always
    container_name: "doc-pgsql-container"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Password1
    networks:
      - app-network

  backend:
    image: 'devops-demo:latest'
    build:
      context: .
      dockerfile: Dockerfile.backend 
    container_name: 'devops-demo-container'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=Password1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # This one is correct for the frontend
    container_name: 'viatab-frontend-container'
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local