apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
  # Optional nodePort specify the external port
  # nodePort: 30001