name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build backend
        run: |
          cd devops-demo
          mvn clean package

      - name: Run Backend GET-Only Tests
        run: |
          cd devops-demo # Ensure correct directory
          mvn test #  Adjust if you have specific GET tests

      # Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: devops-demo/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('devops-demo/frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build frontend
        run: |
          cd devops-demo/frontend
          npm ci
          npm run build

      - name: Run Frontend Tests
        run: |
          cd devops-demo/frontend
          npm test -- --watchAll=false

  build-docker-images:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: devops-demo # Changed from . to ./backend
          dockerfile: Dockerfile.backend #added
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: devops-demo # Changed from . to ./frontend
          dockerfile: Dockerfile #added
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-kubernetes:
    needs: build-docker-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Load images into Minikube
        run: |
          eval $(minikube -p minikube docker-env)
          docker pull ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          docker pull ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          minikube image load ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          minikube image load ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/db-pv.yaml
          kubectl apply -f k8s/db-pvc.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/postgres-service.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get services
          kubectl get deployments

      - name: Wait for deployments to be ready
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/postgres-db
          kubectl wait --for=condition=available --timeout=300s deployment/backend
          kubectl wait --for=condition=available --timeout=300s deployment/frontend

      - name: Get service URLs
        run: |
          minikube service frontend-service --url
          minikube service backend-service --url
